name: minimalist_oats_calendar
description: Minimalist OATS weekly schedule with local storage and Google Drive sync.
publish_to: "none"
version: 1.3.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
